#SERVER CONFIGURATION
server.port=8081
server.context.path=/appzillonbankingcob
#SERVER CONFIGURATION

ab.common.interFaceDir=/app/resources/intfJSON/
ab.common.casaReport=/Unnati_Image/Resources/Microservices/report/casaReport/
ab.common.casaImages=/Unnati_Image/Resources/Microservices/images/casaImages/
ab.common.ccReport=/Unnati_Image/Resources/Microservices/report/ccReport/
ab.common.ccImages=/Unnati_Image/Resources/Microservices/images/ccImages/
ab.common.depositReport=/Unnati_Image/Resources/Microservices/report/depositReport/
ab.common.depositImages=/Unnati_Image/Resources/Microservices/images/depositImages/
ab.common.loanReport=/Unnati_Image/Resources/Microservices/report/loanReport/
ab.common.loanImages=/Unnati_Image/Resources/Microservices/images/loanImages/
ab.common.jsonDir=/app/resources/report/DATAFILES/
ab.common.images=/app/resources/images/

#-------------------------------------------
management.endpoints.web.exposure.include=*
#-------------------------------------------
swagger2markup.generatedExamplesEnabled=true
#-------------------------------------------

#COMMON VALUES FOR APPLICATION
ab.common.litFilePath=/Unnati_Image/Resources/Microservices/props/COB LITCODES_
ab.common.litFileFormat=csv
ab.common.cobFlags=/app/properties/COB_FLAGS.properties
#END COMMON VALUES FOR APPLICATION

spring.quartz.job-store-type = jdbc
spring.quartz.properties.org.quartz.threadPool.threadCount = 5

#Connection Pooling parameters
connectionparams.maxTotalConnections=40
connectionparams.maxRouteConnections=40
connectionparams.maxLocalHostConnections=80
connectionparams.defaultKeepAliveTime=20000
connectionparams.connectionTimeout=30000
connectionparams.requestTimeout=30000
connectionparams.socketTimeout=60000
connectionparams.idleConnectionWaitTime=30000
connectionparams.taskSchedulerPoolSize=5
connectionparams.hostIp=http://localhost
connectionparams.hostPortNumber=5432

#SOAP Connection Pooling parameters
ab.common.connectTimeout=30000
ab.common.readTimeout=30000
ab.common.soapProtocol=SOAP 1.1 Protocol
