#-------------------------------------------
#Spring Boot Jpa Config
spring.main.allow-bean-definition-overriding=true
#-------------------------------------------
#BEGIN DATABASE CONNECTION CONFIGURATION
#-------------------------------------------
#Begin Schema 1 Confiuration
#-------------------------------------------
springcob.datasource.jdbc-url=jdbc:postgresql://172.16.9.153:5004/APZCOB_PREPROD2
springcob.datasource.url=jdbc:postgresql://172.16.9.153:5004/APZCOB_PREPROD2
springcob.datasource.hikari.driver-class-name=org.postgresql.Driver
springcob.datasource.maximum-pool-size=350
springcob.datasource.minimum-idle=5
springcob.datasource.username=unnatiappuser
springcob.datasource.password=K72P9j9gLTgEAFL6jpKbovx5SRELJ3SmE2w8jGvdecEMikN1OSsU69Yea08R2ruxiuVbrgd5NCZwWBXd1hdyFA==
springcob.datasource.driverClassName=org.postgresql.Driver
springcob.datasource.database=POSTGRESQL
springcob.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#-------------------------------------------
#Begin Schema 2 Confiuration
#-------------------------------------------
apzcob.datasource.jdbc-url=jdbc:postgresql://172.16.9.153:5004/APPZILLONCOB_PREPROD2
apzcob.datasource.url=jdbc:postgresql://172.16.9.153:5004/APPZILLONCOB_PREPROD2
apzcob.datasource.hikari.driver-class-name=org.postgresql.Driver
apzcob.datasource.maximum-pool-size=50
apzcob.datasource.minimum-idle=5
apzcob.datasource.username=unnatiappuser
apzcob.datasource.password=LWUQhWwSlEZpSXpTbvTbbkAIrmuh8jkl1s6g8yiH+eCYIj2UfaAYxN9rAL500lDWCKcL3s+WsI2mI4NPE/RKuw==
apzcob.datasource.driverClassName=org.postgresql.Driver
apzcob.datasource.database=POSTGRESQL
apzcob.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#-------------------------------------------
#Begin Schema 3 Confiuration
#-------------------------------------------
cdhcob.datasource.jdbc-url=jdbc:mysql://172.16.108.10:4402/unifiedapp_test?useSSL=false
cdhcob.datasource.url=jdbc:mysql://172.16.108.10:4402/unifiedapp_test?useSSL=false
cdhcob.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
cdhcob.datasource.maximum-pool-size=50
cdhcob.datasource.minimum-idle=5
cdhcob.datasource.username=unifieduat
cdhcob.datasource.password=fHkVAAcSmWn1BlFDro7R48U6ofKY5nsk/CXh+MN8nx0iuqqLPtojz6Pjw7zbTJsv
cdhcob.datasource.driverClassName=com.mysql.cj.jdbc.Driver
cdhcob.datasource.database=mysql
cdhcob.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
cdhcob.datasource.hibernate.hbm2ddl.auto=none
#-------------------------------------------
#Begin Schema 4 Confiuration
#-------------------------------------------
#DigiAgil Config
# usercob.datasource.jdbc-url=jdbc:mysql://172.16.103.10:4402/gk_customer_r19?allowPublicKeyRetrieval=true&useSSL=false
# usercob.datasource.url=jdbc:mysql://172.16.103.10:4402/gk_customer_r19?allowPublicKeyRetrieval=true&useSSL=false
# usercob.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
# usercob.datasource.maximum-pool-size=50
# usercob.datasource.minimum-idle=5
# usercob.datasource.username=Dbiexceeduser
# usercob.datasource.password=uiGubGcfXa/h7p0bVdJjjsFeCJyO8jhIroWkPfZhQ275EC7qfJixro1DfMlJf0lk
# usercob.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# usercob.datasource.database=mysql
# usercob.datasource.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# usercob.datasource.hibernate.hbm2ddl.auto=none
# usercob.datasource.hibernate.mapping-resources=com.iexceed.appzillonbanking.cob.loans.domain.user.KendraDetails

#Maitri config
usercob.datasource.jdbc-url=jdbc:postgresql://172.16.38.47:5004/grameenkoota
usercob.datasource.url=jdbc:postgresql://172.16.38.47:5004/grameenkoota
usercob.datasource.hikari.driver-class-name=org.postgresql.Driver
usercob.datasource.maximum-pool-size=50
usercob.datasource.minimum-idle=5
usercob.datasource.username=cagl
usercob.datasource.password=DgzrPfgIxeVWD3nLPjCVZf5AR3hvQeRAN1UaVbnpmM5T8uZJjAFQzMbFRBszvo8EAjVUOZy0qWJACzUjQ5YY0A==
usercob.datasource.driverClassName=org.postgresql.Driver
usercob.datasource.database=POSTGRESQL
usercob.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#-------------------------------------------
#Begin Common Database settings
#-------------------------------------------
spring.jpa.generate-ddl=true
#spring.jpa.database=default
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.database= POSTGRESQL
spring.jpa.hibernate.ddl-auto = none
#-------------------------------------------
#END DATABASE CONNECTION CONFIGURATION
#-------------------------------------------